"""add_gamification_tables

Revision ID: 893e0738bbce
Revises: f9cff9846534
Create Date: 2025-03-17 11:51:59.066571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893e0738bbce'
down_revision: Union[str, None] = 'f9cff9846534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=False),
    sa.Column('unlock_condition', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('adventure_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('background_image', sa.String(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adventure_maps_id'), 'adventure_maps', ['id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('completed_locations', sa.String(), nullable=True),
    sa.Column('unlocked_achievements', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_table('map_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('unlocked_by_location_id', sa.Integer(), nullable=True),
    sa.Column('adventure_map_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adventure_map_id'], ['adventure_maps.id'], ),
    sa.ForeignKeyConstraint(['unlocked_by_location_id'], ['map_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_locations_id'), 'map_locations', ['id'], unique=False)
    op.create_table('task_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('reward_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['map_locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_groups_id'), 'task_groups', ['id'], unique=False)
    op.add_column('tasks', sa.Column('task_group_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('reward_points', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('difficulty_level', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('estimated_time_seconds', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'task_groups', ['task_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'estimated_time_seconds')
    op.drop_column('tasks', 'difficulty_level')
    op.drop_column('tasks', 'reward_points')
    op.drop_column('tasks', 'task_group_id')
    op.drop_index(op.f('ix_task_groups_id'), table_name='task_groups')
    op.drop_table('task_groups')
    op.drop_index(op.f('ix_map_locations_id'), table_name='map_locations')
    op.drop_table('map_locations')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_adventure_maps_id'), table_name='adventure_maps')
    op.drop_table('adventure_maps')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
