"""add_avatar_id_to_users

Revision ID: c5ba536070a4
Revises: 28059c6bfcb3
Create Date: 2025-03-25 10:19:47.693235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ba536070a4'
down_revision: Union[str, None] = '28059c6bfcb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_id')
    # ### end Alembic commands ###
